name: Auto Merge Context Updates

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.title == '🤖 Automatische Kontext-Aktualisierung'
    
    steps:
    - name: Wait for 5 minutes
      run: sleep 300
      
    - name: Auto merge
      uses: actions/github-script@v7
      with:
        script: |
          try {
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash',
              commit_title: '🤖 Automatische Kontext-Aktualisierung',
              commit_message: 'Automatischer Merge durch GitHub Action'
            });
            console.log('✅ Pull Request erfolgreich gemergt');
          } catch (error) {
            console.log('❌ Merge fehlgeschlagen:', error.message);
          } 